"$schema" = 'https://starship.rs/config-schema.json' 

add_newline = true

format = '''
$dotnet$nodejs$fill$time
$directory$fill$git_state$git_branch$git_status
[󰄾](bold green) '''

[directory]
truncate_to_repo = true
format = '[$read_only]($read_only_style)[$path]($style)' 

[git_branch]
format ="[$symbol$branch(:$remote_branch)]($style) "

[git_status]
conflicted = "󱐌"
untracked = "󰘓"
stashed = ""
deleted = "󰆴"

[fill]
symbol = " "

[time]
disabled = false
format = "[]($style) [$time]($style)"
style = "italic bright-black"

